pipeline{
	agent any
	tools {
  maven 'maven3'
        }

	stages{
	 stage('Git checkout'){
	   steps{
	  git credentialsId: 'gitHub',
	  url: 'https://github.com/Apurb1994/Apurb-Devops'
	}
 	}
 
  stage('mvn clean package'){
	   steps{
	 sh 'mvn clean package'
	}
 	}

	stages{
	 stage('Nexus deploy'){
	   steps{
	 nexusArtifactUploader artifacts: [[artifactId: 'Apurb-Devops', classifier: 'target/Apurb-Devops.war', file: 'target/Apurb-Devops.war', type: 'war']], credentialsId: 'in.javahome', groupId: 'in.javahome', nexusUrl: '172.31.43.5:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'Apurb-test-snapshot', version: '3.0-SNAPSHOT'
	}
 	}	
		
		

  }
}
